config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :billboards do
    resources :artists do
      resources :songs
    end
  end
  

  root 'billboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard, optional: true
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :artists, dependent: :destroy
    has_many :songs, :through => :artists
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :billboards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = @billboard.artists.new
  end

  def edit
  end

  def create
    @artist = @billboard.artists.new(artist_params)

    if @artist.save
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :avatar, :genre)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name, :avatar)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist
  before_action :set_song, only: [:update, :edit, :destroy]

  def index
    @songs = @artist.songs
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to billboard_artists_path
    else
      render :new
    end
  end

  def destroy
    @song.destroy
    redirect_to [@billboard, @artist]
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :avatar, :length)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1 class="ui header"><%= @artist.id ? 'Edit Artist' : 'Add Artist' %></h1>
<hr />
<%= form_with(model: [@billboard, @artist], local: true, class: "ui form") do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, require: true, autofocus: true %>
    <br />
    <%= f.label :avatar %>
    <%= f.text_field :avatar, placeholder: "Type something here..." %>
    <br />
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br />
    <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", billboard: @billboard, artist: @artist %>

<%= link_to 'Back', billboard_artists_path(@billboard) %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", billboard: @billboard, artist: @artist %>

<%= link_to 'Back', billboard_artists_path(@billboard) %>

app/views/artists/show.html.erb
<br />
<%= link_to 'Home', billboards_path %>
<h1 class="ui header">
  <img src="https://robohash.org/<%= @artist.avatar %>?set=set2" class="ui circular image">
  <%= @artist.name %>
<br />
  <button class="ui basic button"><i class="icon music"></i><%= link_to 'Add Song', new_billboard_artist_song_path(@billboard, @artist) %></button>
</h1>
<h2>Songs</h2>
  <%= render 'songs/song' %>
<br />

app/views/billboards/_form.html.erb
<h1>Add A Billboard</h1>
<%= form_for @billboard do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: 'Billboard Name' %>
    <br />
    <%= f.label :avatar %>
    <%= f.text_field :avatar, placeholder: 'Type something here...' %>
    <br />
    <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard</h1>

<%= render "form", billboard: @billboard %>

<%= link_to "Show", billboard_path(@billboard) %> |
<%= link_to "Back", billboards_path %>

app/views/billboards/index.html.erb
<div class="ui button">
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
</div>
<h1 class="ui block header">Billboards</h1>
<%= link_to 'Create a new Billboard', new_billboard_path %>
<div class="ui divider"></div>

<div class="ui grid">
    <% @billboards.each do |billboard| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
        <div class="ui card">
            <div class="image">
                <img src="https://robohash.org/<%= billboard.avatar %>?set=set2" />
            </div>
            <div class="content">
                <%= link_to "#{billboard.name}", billboard, class: "header" %>
            </div>
            <div class="extra content">
                <div class="ui two buttons">
                    <div class="ui basic green button">
                        <%= link_to 'Edit', edit_billboard_path(billboard) %>
                    </div>
                    <div class="ui basic red button">
                        <%= link_to 'Destroy', billboard, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/billboards/new.html.erb
<h1>New Billboard</h1>

<%= render "form", billboard: @billboard %>

<%= link_to "Back", billboards_path %>

app/views/billboards/show.html.erb
<h1 class="ui header">
  <img src="https://robohash.org/<%= @billboard.avatar %>?set=set2" class="ui circular image">
  <%= @billboard.name %>
  <br />
  <button class="ui basic button"><i class="icon music"></i><%= link_to 'Add Artists', new_billboard_artist_path(@billboard)%></button>
</h1>

<div class="ui grid">
    <% @billboard.artists.each do |artist| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
        <div class="ui card">
            <div class="image">
                <img src="https://robohash.org/<%= artist.avatar %>?set=set2" />
            </div>
            <div class="content">
                <%= link_to "#{artist.name}", billboard_artist_path(@billboard), class: "header" %>
            </div>
            <div class="extra content">
                <div class="ui two buttons">
                    <div class="ui basic green button">
                        <%= link_to 'Edit', [@billboard, @artist] %>
                    </div>
                    <div class="ui basic red button">
                        <%= link_to 'Destroy', @artist, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="ui container">
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1>Add a Song</h1>
<%= form_for [@billboard, @artist, @song], class: "ui form" do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
    <br />
    <%= f.label :avatar %>
    <%= f.text_field :avatar, placeholder: "Type something here..." %>
    <br />
    <%= f.label :length %>
    <%= f.text_field :length %>
    <br />
    <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/songs/_song.html.erb
<table class="ui striped table">
    <thead>
        <tr class="center aligned">
            <th colspan="4"></th>
        </tr>
    </thead>

    <tbody>
    <% @artist.songs.each do |song| %>
            <tr class="center aligned">
                <td>
                    <img class="ui avatar image small" src="https://robohash.org/<%= song.avatar %>?set=set3">
                </td>
                <td>
                    <%= song.name %>
                </td>
                <td>
                    <%= song.length %>
                </td>
                <td>
                    <%= link_to '☠︎', [@billboard, @artist, song], method: :delete %>
                </td>
            </tr>
    <% end %>
    </tbody>
</table>

app/views/songs/_songs.html.erb
<table class="ui striped table">
    <thead>
        <tr class="center aligned">
            <th colspan="4"></th>
        </tr>
    </thead>

    <tbody>
            <tr class="center aligned">
                <td>
                    <img class="ui avatar image small" src="https://robohash.org/<%= @song.avatar %>?set=set4">
                </td>
                <td>
                    <%= @song.name %>
                </td>
                <td>
                    <%= @song.length %>
                </td>
                <td>
                    <%= link_to 'Artist', artist_songs_path(@billboard) %>
                    <%= link_to '☠︎', [@billboard, @song], method: :delete %>
                </td>
            </tr>
    </tbody>
</table>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render "form", billboard: @billboard, artist: @artist, song: @song %>